### PR TITLE
Functional component

### LINKED ISSUE #2: ui-react-starter: missing package-lock.json
Hi there!

Thanks for providing these great examples. I've been able to successfully load a few of them but I was having an issue with `ui-react-starter`. When running `yarn install` the `preinstall` script is kicking off and it is requiring a `package-lock.json` that doesn't exist. 

Since the guide for this plugin is recommending to use `yarn` it is safe to remove the use of the `preinstall` script because the sole purpose of `npm-force-resolutions` is to mimic yarn's dependencies resolution without needing yarn. We will also need to commit the `yarn.lock` to make it work properly.

With these changes I am able to run the plugin on my end:

Screen Shot 2020-10-20 at 6 10 41 PM

Happy to submit a PR if needed but the repo is currently not open to outside contributions :)

### LINKED ISSUE #4: ui-react-starter: doens't compile
Having went through the setup guidelines and picking react starter, running `npm run watch` results in an error:

```
Built at: 02/02/2021 9:37:48 AM
              Asset       Size  Chunks             Chunk Names
   icons/icon_D.png  568 bytes          [emitted]  
icons/icon_D@2x.png   1.01 KiB          [emitted]  
   icons/icon_N.png  535 bytes          [emitted]  
icons/icon_N@2x.png  995 bytes          [emitted]  
         index.html  186 bytes          [emitted]  
           index.js   2.47 MiB    main  [emitted]  main
            main.js  897 bytes          [emitted]  
      manifest.json   1.76 KiB          [emitted]  
Entrypoint main = index.js
[./node_modules/css-loader/dist/cjs.js!./src/styles.css] 563 bytes {main} [built]
[./src/controllers/CommandController.jsx] 365 bytes {main} [built] [failed] [1 error]
[./src/controllers/PanelController.jsx] 364 bytes {main} [built] [failed] [1 error]
[./src/index.jsx] 1.61 KiB {main} [built]
[./src/panels/Demos.jsx] 272 bytes {main} [built]
[./src/panels/MoreDemos.jsx] 546 bytes {main} [built]
[./src/styles.css] 520 bytes {main} [built]
[os] external "os" 42 bytes {main} [built]
[uxp] external "uxp" 42 bytes {main} [built]
    + 21 hidden modules

ERROR in ./src/controllers/PanelController.jsx 4:2
Module parse failed: Unexpected character '#' (4:2)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import ReactDOM from "react-dom";
| export class PanelController {
>   #id = null;
|   #root = null;
|   #attachment = null;
 @ ./src/index.jsx 4:0-68 22:28-43 38:32-47

ERROR in ./src/components/ColorPicker.jsx 5:2
Module parse failed: Unexpected character '#' (5:2)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import "./ColorPicker.css";
| export class ColorPicker extends React.Component {
>   #sldR;
|   #sldG;
|   #sldB;
 @ ./src/panels/Demos.jsx 2:0-60 5:99-110
 @ ./src/index.jsx

ERROR in ./src/controllers/CommandController.jsx 8:2
Module parse failed: Unexpected character '#' (8:2)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import ReactDOM from "react-dom";
| export class CommandController {
>   #id = null;
|   #root = null;
|   #Component = null;
 @ ./src/index.jsx 5:0-72 10:28-45
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! com.adobe.uxp.starter.react@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 2
```

### LINKED ISSUE #5: ui-react-starter: .gitignore missing
As a good practice, it would be helpful to have sample-specific .gitignore file that could include `dist` and `node_modules`

### LINKED ISSUE #6: ui-react-starter: provide functional react sample
Modern react development practices favour functional react and hooks rather than classes. Having a sample with classes can confuse new developers who don't yet have a lot of experience.

It would be great to either have current starter re-written in a functional way or provide a functional starter.

### PR DESCRIPTION
**Pull request by aviral243**
- Ported components to functional react definition.
- Replaced private properties with `Symbol` static properties to fix compiling issues with `npm`.
- Added a project specific `.gitignore`.
- Made appropriate changes to the README
- Commit `package-lock` and `yarn.lock` to prevent version conflicts 

- Fixes #6 
- Fixes #5 
- Fixes #4 
- Fixes #2

### CODE REVIEW

**Review by kerrishotts — APPROVED** [review]
This is amazing! I have no nits to pick :-)

File: ui-react-starter/src/components/About.jsx [hunk 1]
```diff
@@ -5,33 +5,31 @@ import os from "os";
...
+        <sp-detail>VERSIONS</sp-detail>
+        <div className="table">
+            <div><sp-detail>PLUGIN: </sp-detail><sp-body> {versions.plugin}</sp-body></div>
+            <div><sp-detail>OPERATING SYTEM:</sp-detail><sp-body> {os.platform()} {os.release()}</sp-body></div>
+            <div><sp-detail>UNIFIED EXTENSIBILITY PLATFORM:</sp-detail><sp-body>{versions.uxp}</sp-body></div>
+        </div>
+        <sp-button-group>
+            <sp-button tabindex={0} variant="secondary" quiet="quiet" onClick={() => this.props.dialog.close("reasonCanceled")}>Cancel</sp-button>
+            <sp-button tabindex={0} autofocus="autofocus" variant="primary" onClick={() => this.props.dialog.close("ok")}>Ok</sp-button>
+        </sp-button-group>
```
Comment (ashryanbeats) [inline ui-react-starter/src/components/About.jsx:32]: A couple of things here:

1. Can you make sure the dialog closes when these buttons are clicked? Wild guess, but it might be worth checking if `.dialog` is being passed in `this.props`.
2. Minor nit: Change "Ok" to "OK"

These may have been issues in the original sample as well, and this is a good time to fix them.

File: ui-react-starter/src/components/About.jsx [hunk 2]
```diff
@@ -5,33 +5,31 @@ import os from "os";
...
+        <sp-heading>React Starter Plugin</sp-heading>
+        <sp-divider size="large"></sp-divider>
+        <sp-body>
+            This is a simple plugin that demonstrates the various capabilities of React on UXP.
+            When adapting to your own projects, you can replace <code>index.jsx</code> and the components
+            with your own. 
+        </sp-body>
+        <sp-body class="well">
+            <sp-icon name="ui:InfoSmall" size="s"></sp-icon>
+            We've also included the `WC` component and a couple of controlelrs. You
```
Comment (ashryanbeats) [inline ui-react-starter/src/components/About.jsx:20]: Fix spelling of "controllers"

**Review by ashryanbeats — CHANGES_REQUESTED** [review]
Great work! A couple of changes requested inline on `About.jsx`.

File: ui-react-starter/src/components/About.jsx (hunk 1 above)
Comment (aviral243) [reply ui-react-starter/src/components/About.jsx]: > These may have been issues in the original sample as well, and this is a good time to fix them.

Well, typos were present, but the buttons were not working due to something I messed up (didn't pass props to the functional component). :p
This should be fixed now.

File: ui-react-starter/src/components/About.jsx (hunk 2 above)
Comment (aviral243) [reply ui-react-starter/src/components/About.jsx]: Done.

File: ui-react-starter/src/components/About.jsx (hunk 1 above)
Comment (ashryanbeats) [reply ui-react-starter/src/components/About.jsx]: Nice!

**Review by ashryanbeats — APPROVED** [review]

**Comment by ashryanbeats** [comment]
Thanks for the pull request! You have pulled our React sample into the future 🎉
